config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/',to: 'home_page#home' 
  get '/contact', to:'contact#contact' 
  get '/find_user/:user', to:'contact#find_user' 
  get '/find_gossip/:gossip', to:'home_page#find_gossip', as: 'find_gossip' 
  get '/find_author/:user', to:'home_page#find_author', as: 'find_author' 
  post '/user/login', to: 'session#create', as: 'signin_action' 
  get '/gossip/create', to: 'home_page#create_gossip_view'
  post '/gossip/create',to: 'home_page#create_gossip',as: 'create_gossip'
  get '/user/login',to:'session#createsessionview'
  post '/user/signup',to: 'home_page#signup', as: 'signup_action'
  get '/user/signup', to: 'home_page#signupview' 
  get '/user/signout', to:'session#logout' 
  post '/gossip/modify/:gossip',to:"home_page#edit_gossip",as: "edit_gossip"
  get '/gossip/modify/:gossip', to:"home_page#edit_gossip_view" 
  get '/gossip/delete/:gossip', to:"home_page#delete_gossip", as:"delete_gossip" 
  get '/gossip/like/:gossip',to:"home_page#like_gossip",as: "like_gossip"
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord 
    belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user 
    has_many :tags_gossips 
    has_many :tags, through: :tags_gossips 
    has_many :comments 
    has_many :likes
end

app/models/like.rb
class Like < ApplicationRecord 
    belongs_to :gossip
    belongs_to :user
end

app/models/like_gossip.rb
class LikeGossip < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord 
    belongs_to :user 
    has_many :private_message_users 
    has_many :users, through: :private_message_users
end

app/models/private_message_user.rb
class PrivateMessageUser < ApplicationRecord 
    belongs_to :user 
    belongs_to :private_message
end

app/models/tag.rb
class Tag < ApplicationRecord 
    has_many :tags_gossips 
    has_many :gossips, through: :tags_gossips
end

app/models/tags_gossip.rb
class TagsGossip < ApplicationRecord 
    belongs_to :tag 
    belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord  
    has_secure_password
    has_many :gossips 
    belongs_to :city

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

    def contact 
        
        @users=User.all 
        puts "GET USERS"
        puts @users.length

    end 

    def find_user
        @user=params[:user]

    end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
    def home 
        gossips=Gossip.all 

        if gossips
         
            @gossips=gossips
           

            
        else 
            @message="Bienvenue a la page des Potins!,il n'y a pas encore des potins ecrit"
        end
        
    end 

    def find_gossip 
        @gossip=Gossip.find(params[:gossip])
    end  

    def create_gossip_view 
        if session[:user_id]==nil 
            flash[:danger]="Utilisateur non connecté"
            redirect_to "/"
        end
    end

    def create_gossip 

        puts "GET PARAMS"
        puts params
        user=User.find(session[:user_id])
        Gossip.create(title:params[:title],content:params[:content],user:user)
        flash[:success]="Potin bien crée"
        redirect_to '/'
    end

    def find_author
        @user=User.find(params[:user])
    end 
    
    def signupview 
        @cities=City.all
    end

    def signup 
        
        city=City.find(params[:city])
        user=User.create(firstname:params[:firstname],lastname:params[:lastname],email:params[:email],password:params[:password],city:city,age:25,description:"this is the usres descripton profile");
        flash[:success] = "User bien crée! !"

        redirect_to '/' 
    end 

    def edit_gossip_view 
        @gossip=Gossip.find(params[:gossip])
    end 

    def edit_gossip 
        gossip=Gossip.find(params[:gossip]);
        
        gossip.title=params[:title]
        gossip.content=params[:content] 
        gossip.save
        redirect_to '/'
    end 

    def delete_gossip 
        Gossip.destroy(params[:gossip])
        redirect_to '/'
        
    end 

    def like_gossip 
        user=User.find(session[:user_id]);
        gossip=Gossip.find(params[:gossip])
        
        find_like=Like.where(gossip:gossip,user:user)
       
        if find_like.length==0
            Like.create(user:user,gossip:gossip) 
            redirect_to '/'

        else 
            Like.destroy(find_like.ids) 
            redirect_to '/'

        end
       

       
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController 
    def create 
          email=params[:email]
          user=User.find_by(email:email) 

        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            # redirige où tu veux, avec un flash ou pas
            redirect_to '/'
        
          else
            flash.now[:danger] = 'Invalid email/password combination'
            
          end
       
    end 

    def logout
        session.delete(:user_id)
        redirect_to '/'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/session_helper.rb
module SessionHelper
    
end

app/views/contact/contact.erb
<h1> Contact: 100 rue de THP, LA LUNE LuneVille 1000 </h1> 

<br/>

<div> Bienvenue a notre equipe </div> 

<br/>
<div> Voici nos membres </div>  
<br/>





<% @users.each do |user| %>  
<div> Prenom: <%=user.firstname %> 
<div> Nom : <%=user.lastname %>  </div> 
<div> Description: <%=user.description %> </div>
<br/>

<% end %>

app/views/contact/find_user.erb
<h4> Targeted User: <%=@user %>  </h4>

app/views/home_page/create_gossip_view.erb
<h2> This is the signup page </h2>

<%= form_with url:create_gossip_url , method: :post do |form| %>
<div> 
  <%= form.label :title, "titre" %>
  <%= form.text_field :title, size:"20x10" %> 
</div> 



<div> 
     <%= form.label :content, "contenu" %>
     <%= form.text_area :content %> 
</div>



  <%= form.submit "Envoyer" %>
<% end %>

app/views/home_page/edit_gossip_view.erb
<h2> This is the signup page </h2>

<%= form_with url:edit_gossip_url(@gossip.id) , method: :post do |form| %>
<div> 
  <%= form.label :title, "titre" %>
  <input type="text" value=<%=@gossip.title %> name="title" />
</div> 



<div> 
     <%= form.label :content, "contenu" %>
     <textarea name="content" rows=20 cols=20> <%=@gossip.content %></textarea>
</div>



  <%= form.submit "Envoyer" %>
<% end %>

app/views/home_page/find_author.erb
<h2> Infos de l'auteur </h2> 

<div> prenom: <%=@user.firstname %> </div> 
<div> nom: <%=@user.lastname %> </div> 
<div> email: <%=@user.email %> </div>

app/views/home_page/find_gossip.erb
<h2> Infos du gossip </h2> 

<div> Titre: <%=@gossip.title %> </div> 
<div> Contenu: <%=@gossip.content %> </div>

app/views/home_page/home.erb
<% if session[:user_id] %>
<h2> Bienvenue a mon projet de gossips </h2> 
<br/>
    <% if @gossips.length>0 %>
    <% @gossips.each do |gossip| %>
    <div> Titre: <%=gossip.title %> </div> 
    <div> Contenu: <%=gossip.content %></div> 
    <div> <%=link_to "voir le gossip",find_gossip_url(gossip.id) %></div> 
     <div> <%=link_to "voir l'auteur",find_author_url(gossip.user.id) %>  </div>  
     <div> <%=link_to "liker ce potin",like_gossip_url(gossip.id) %> Nombre de Likes: <span> <%=gossip.likes.length %> </span></div>
     <% if gossip.user.id==session[:user_id] %>
        <div> <%=link_to "editer le potin",edit_gossip_url(gossip.id) %> </div>
        <div> <%=link_to "supprimer le potin",delete_gossip_url(gossip.id) %> </div> 
        
     <% end %>
    <br/> 
    <% end %> 
    <% else %>
    <h2>  Pas Encore de Potins Ecrit </h2>
    <% end %> 
    <h4> Vous voulez ecrire un Potin ? </h4> 
    <div> <%=link_to "ecrire un potin",create_gossip_url %> </div>
  

<% else %>
<h2> Bienvenue a la page d'accueil, viullez vous inscrire ou vous connectez si vous avez deja un compte ! </h2>


<% end %>

app/views/home_page/signupview.erb
<h2> This is the signup page </h2>

<%= form_with url:signup_action_url , method: :post do |form| %>
<div> 
  <%= form.label :firstname, "Votre Prenom" %>
  <%= form.text_field :firstname %> 
</div> 



<div> 
     <%= form.label :lastname, "Votre Nom" %>
     <%= form.text_field :lastname %> 
</div>

<div> 
     <%= form.label :email, "Votre Email" %>
     <%= form.email_field :email %> 
</div> 

<div> 
     <%= form.label :password, "Votre Mot De Passe" %>
     <%= form.password_field :password %> 
</div> 
<div> 
 <div class="form-group">
  <%= form.label :city, "Dans quelle ville viviez vous?" %>
    <%= form.select :city, @cities.map { |city| [city.name, city.id]}, {} %>
  </div>

  <%= form.submit "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 


  <header class="bg-info p-3">  

  <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
  <% if session[:user_id] %>
  <div class="d-flex justify-content-around"> 
    <div class="text-white"> This Is My Header </div>  
    <div class="mr-2"> <%= link_to "Voir Equipe", "/contact" %> </div> 
      <div class="mr-2"> <%= link_to "Deconnexion", "/user/signout" %> </div> 
    
    <div> <%= link_to "Accueil", "/" %> 
  </div>  

    <% else %>
    <div class="d-flex justify-content-around"> 
    <div class="text-white"> This Is My Header </div>  
    <div class="mr-2"> <%= link_to "Inscription", "/user/signup" %> </div> 
    <div class="mr-2"> <%= link_to "Connexion", "/user/login" %> </div> 
   
    
    <div> <%= link_to "Accueil", "/" %> 
  </div>  
    <% end %>
     
  </header>
    <%= yield %>
  </body>
</html>

app/views/session/createsessionview.erb
<h2> This is the signin page </h2>

<%= form_with url:signin_action_url , method: :post do |form| %>


<div> 
     <%= form.label :email, "Votre Email" %>
     <%= form.email_field :email %> 
</div> 

<div> 
     <%= form.label :password, "Votre Mot De Passe" %>
     <%= form.password_field :password %> 
</div> 
<div> 
 

  <%= form.submit "Search" %>
<% end %>